name: Android CI (Debug APK)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: gradle/gradle-build-action@v3

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Create Gradle wrapper (if missing)
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "Gradle wrapper missing; generating..."
            sudo apt-get update && sudo apt-get install -y gradle
            gradle wrapper --gradle-version 8.7
            chmod +x gradlew
          fi

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleHelloApp-debug-apk
          path: app/build/outputs/apk/debug/*.apk
