name: Android Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Make sure Gradle wrapper is executable (common cause of "no APK")
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Use JDK 17 (required by recent Android Gradle Plugin versions)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Optional but speeds up builds
      - name: Setup Gradle cache
        uses: gradle/gradle-build-action@v3

      # Install Android SDK components (build-tools + platforms).
      # Adjust versions to match your project’s compileSdk/buildTools.
      - name: Install Android SDK components
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-34
            build-tools;34.0.0
            platform-tools

      # Build the debug APK. If your module is NOT "app", change ":app:" below.
      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --stacktrace

      # Upload the generated APK(s) as artifacts for easy download.
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
